#!/bin/sh

set -e

echo "Disabling Developer Mode..."

echo "root=/dev/mmcblk0p2 rootwait console=tty1 console=ttyAMA0,115200 vt.global_cursor_default=0 quiet" > /boot/cmdline.txt
rm /etc/mediaberry/devmode

echo "Developer Mode has been disabled!"
