#!/bin/sh

if [ -f /etc/mediaberry/devmode ]
then
	echo "mediaberryd: developer mode is enabled"
fi

# Mount the /boot partition

echo "mediaberryd: mounting /boot"

mkdir /boot
mount /dev/mmcblk0p1 /boot

# prepare environment variables

echo "mediaberryd: preparing environment variables"

source /etc/profile
export HOME=/root
cd /root

# start xorg, which handles the rest of what we need to do with .xinitrc

echo "mediaberryd: starting mediaberry"

startx
